/* toast */

var toastTrigger = document.getElementById('liveToastBtn')
var toastLiveExample = document.getElementById('liveToast')

if (toastTrigger) {
  toastTrigger.addEventListener('click', function () {
    var toast = new bootstrap.Toast(toastLiveExample)

    toast.show()
  })
}
  

var toastTrigger2 = document.getElementById('liveToastBtn2')
var toastLiveExample2 = document.getElementById('liveToast2')

if (toastTrigger2) {
  toastTrigger2.addEventListener('click', function () {
    var toast2 = new bootstrap.Toast(toastLiveExample2)

    toast2.show()
  })
}

var toastTrigger3 = document.getElementById('liveToastBtn3')
var toastLiveExample3 = document.getElementById('liveToast3')

if (toastTrigger3) {
  toastTrigger3.addEventListener('click', function () {
    var toast3 = new bootstrap.Toast(toastLiveExample3)

    toast3.show()
  })
}

var toastTrigger4 = document.getElementById('liveToastBtn4')
var toastLiveExample4 = document.getElementById('liveToast4')

if (toastTrigger4) {
  toastTrigger4.addEventListener('click', function () {
    var toast4 = new bootstrap.Toast(toastLiveExample4)

    toast4.show()
  })
}

var toastTrigger5 = document.getElementById('liveToastBtn5')
var toastLiveExample5 = document.getElementById('liveToast5')

if (toastTrigger5) {
  toastTrigger5.addEventListener('click', function () {
    var toast5 = new bootstrap.Toast(toastLiveExample5)

    toast5.show()
  })
}

var toastTrigger6 = document.getElementById('liveToastBtn6')
var toastLiveExample6 = document.getElementById('liveToast6')

if (toastTrigger6) {
  toastTrigger6.addEventListener('click', function () {
    var toast6 = new bootstrap.Toast(toastLiveExample6)

    toast6.show()
  })
}

var toastTrigger7 = document.getElementById('liveToastBtn7')
var toastLiveExample7 = document.getElementById('liveToast7')

if (toastTrigger7) {
  toastTrigger7.addEventListener('click', function () {
    var toast7 = new bootstrap.Toast(toastLiveExample7)

    toast7.show()
  })
}

var toastTrigger8 = document.getElementById('liveToastBtn8')
var toastLiveExample8 = document.getElementById('liveToast8')

if (toastTrigger8) {
  toastTrigger8.addEventListener('click', function () {
    var toast8 = new bootstrap.Toast(toastLiveExample8)

    toast8.show()
  })
}

var toastTrigger9 = document.getElementById('liveToastBtn9')
var toastLiveExample9 = document.getElementById('liveToast9')

if (toastTrigger9) {
  toastTrigger9.addEventListener('click', function () {
    var toast9 = new bootstrap.Toast(toastLiveExample9)

    toast9.show()
  })
}

var toastTrigger10 = document.getElementById('liveToastBtn10')
var toastLiveExample10 = document.getElementById('liveToast10')

if (toastTrigger10) {
  toastTrigger10.addEventListener('click', function () {
    var toast10 = new bootstrap.Toast(toastLiveExample10)

    toast10.show()
  })
}

var toastTrigger11 = document.getElementById('liveToastBtn11')
var toastLiveExample11 = document.getElementById('liveToast11')

if (toastTrigger11) {
  toastTrigger11.addEventListener('click', function () {
    var toast11 = new bootstrap.Toast(toastLiveExample11)

    toast11.show()
  })
}

var toastTrigger12 = document.getElementById('liveToastBtn12')
var toastLiveExample12 = document.getElementById('liveToast12')

if (toastTrigger12) {
  toastTrigger12.addEventListener('click', function () {
    var toast12 = new bootstrap.Toast(toastLiveExample12)

    toast12.show()
  })
}


var toastTrigger13 = document.getElementById('liveToastBtn13')
var toastLiveExample13 = document.getElementById('liveToast13')

if (toastTrigger13) {
  toastTrigger13.addEventListener('click', function () {
    var toast13 = new bootstrap.Toast(toastLiveExample13)

    toast13.show()
  })
}

var toastTrigger14 = document.getElementById('liveToastBtn14')
var toastLiveExample14 = document.getElementById('liveToast14')

if (toastTrigger14) {
  toastTrigger14.addEventListener('click', function () {
    var toast14 = new bootstrap.Toast(toastLiveExample14)

    toast14.show()
  })
}

var toastTrigger15 = document.getElementById('liveToastBtn15')
var toastLiveExample15 = document.getElementById('liveToast15')

if (toastTrigger15) {
  toastTrigger15.addEventListener('click', function () {
    var toast15 = new bootstrap.Toast(toastLiveExample15)

    toast15.show()
  })
}

var toastTrigger16 = document.getElementById('liveToastBtn16')
var toastLiveExample16 = document.getElementById('liveToast16')

if (toastTrigger16) {
  toastTrigger16.addEventListener('click', function () {
    var toast16 = new bootstrap.Toast(toastLiveExample16)

    toast16.show()
  })
}

var toastTrigger17 = document.getElementById('liveToastBtn17')
var toastLiveExample17 = document.getElementById('liveToast17')

if (toastTrigger17) {
  toastTrigger17.addEventListener('click', function () {
    var toast17 = new bootstrap.Toast(toastLiveExample17)

    toast17.show()
  })
}

var toastTrigger18 = document.getElementById('liveToastBtn18')
var toastLiveExample18 = document.getElementById('liveToast18')

if (toastTrigger18) {
  toastTrigger18.addEventListener('click', function () {
    var toast18 = new bootstrap.Toast(toastLiveExample18)

    toast18.show()
  })
}

var toastTrigger19 = document.getElementById('liveToastBtn19')
var toastLiveExample19 = document.getElementById('liveToast19')

if (toastTrigger19) {
  toastTrigger19.addEventListener('click', function () {
    var toast19 = new bootstrap.Toast(toastLiveExample19)

    toast19.show()
  })
}

var toastTrigger20 = document.getElementById('liveToastBtn20')
var toastLiveExample20 = document.getElementById('liveToast20')

if (toastTrigger20) {
  toastTrigger20.addEventListener('click', function () {
    var toast20 = new bootstrap.Toast(toastLiveExample20)

    toast20.show()
  })
}

var toastTrigger21 = document.getElementById('liveToastBtn21')
var toastLiveExample21 = document.getElementById('liveToast21')

if (toastTrigger21) {
  toastTrigger21.addEventListener('click', function () {
    var toast21 = new bootstrap.Toast(toastLiveExample21)

    toast21.show()
  })
}

var toastTrigger22 = document.getElementById('liveToastBtn22')
var toastLiveExample22 = document.getElementById('liveToast22')

if (toastTrigger22) {
  toastTrigger22.addEventListener('click', function () {
    var toast22 = new bootstrap.Toast(toastLiveExample22)

    toast22.show()
  })
}

var toastTrigger23 = document.getElementById('liveToastBtn23')
var toastLiveExample9 = document.getElementById('liveToast23')

if (toastTrigger23) {
  toastTrigger23.addEventListener('click', function () {
    var toast23 = new bootstrap.Toast(toastLiveExample23)

    toast23.show()
  })
}


var toastTrigger24 = document.getElementById('liveToastBtn24')
var toastLiveExample24 = document.getElementById('liveToast24')

if (toastTrigger24) {
  toastTrigger24.addEventListener('click', function () {
    var toast24 = new bootstrap.Toast(toastLiveExample24)

    toast24.show()
  })
}

var toastTrigger25 = document.getElementById('liveToastBtn25')
var toastLiveExample25 = document.getElementById('liveToast25')

if (toastTrigger25) {
  toastTrigger25.addEventListener('click', function () {
    var toast25 = new bootstrap.Toast(toastLiveExample25)

    toast25.show()
  })
}

var toastTrigger26 = document.getElementById('liveToastBtn26')
var toastLiveExample26 = document.getElementById('liveToast26')

if (toastTrigger26) {
  toastTrigger26.addEventListener('click', function () {
    var toast26 = new bootstrap.Toast(toastLiveExample26)

    toast26.show()
  })
}

var toastTrigger26 = document.getElementById('liveToastBtn26')
var toastLiveExample26 = document.getElementById('liveToast26')

if (toastTrigger26) {
  toastTrigger26.addEventListener('click', function () {
    var toast26 = new bootstrap.Toast(toastLiveExample26)

    toast26.show()
  })
}

var toastTrigger27 = document.getElementById('liveToastBtn27')
var toastLiveExample27 = document.getElementById('liveToast27')

if (toastTrigger27) {
  toastTrigger27.addEventListener('click', function () {
    var toast27 = new bootstrap.Toast(toastLiveExample27)

    toast27.show()
  })
}

var toastTrigger28 = document.getElementById('liveToastBtn28')
var toastLiveExample28 = document.getElementById('liveToast28')

if (toastTrigger28) {
  toastTrigger28.addEventListener('click', function () {
    var toast28 = new bootstrap.Toast(toastLiveExample28)

    toast28.show()
  })
}

var toastTrigger29 = document.getElementById('liveToastBtn29')
var toastLiveExample29 = document.getElementById('liveToast29')

if (toastTrigger29) {
  toastTrigger29.addEventListener('click', function () {
    var toast29 = new bootstrap.Toast(toastLiveExample29)

    toast29.show()
  })
}

var toastTrigger30 = document.getElementById('liveToastBtn30')
var toastLiveExample30 = document.getElementById('liveToast30')

if (toastTrigger30) {
  toastTrigger30.addEventListener('click', function () {
    var toast30 = new bootstrap.Toast(toastLiveExample30)

    toast30.show()
  })
}